export const categories = [
  { name: 'bowls', icon: '/gallery/gallery_2.png' },
  { name: 'carafes', icon: '/gallery/gallery_3.png' },
  { name: 'plats', icon: '/gallery/gallery_4.png' },
  { name: 'vases', icon: '/gallery/gallery_5.png' },
  { name: 'glasses', icon: '/gallery/gallery_6.png' },
];

export const products = [
  // BOWLS
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },

  // CARAFES
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },

  // PLATS
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },

  // VASES
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },

  // GLASSES
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
  {
    id: 'the-good-carafes',
    category: 'carafes',
    src: '/gallery/gallery_3.png',
    title: 'Grand pichet noir',
    price: '€ 8.00',
    details: 'Fait main, au tour',
    material: 'Grès roux de Treigny (Bourgogne)',
    design: 'Émail noir aux nuances marrons',
    dimensions: { diameter: '9cm', height: '19cm' },
    weight: '30g',
    capacity: '700ml',
    description:
      'Toutes les pièces sont entièrement façonnées à la main, tournées et émaillées dans mon atelier à Paris. Étant fabriquées de façon artisanale, il peut donc y avoir de légères variations en terme de dimensions et de couleur par rapport aux photos et entre les différentes pièces d’une même série. Cette vaisselle est adaptée au contact alimentaire et faite pour un usage quotidien. En terme d’entretien, elle passe au lave-vaisselle mais pour la préserver le plus longtemps possible, il est recommandé de la laver à la main avec soin. Elle passe aussi au micro-ondes mais ne convient pas pour le four.',
    images: [
      '/gallery/gallery_1.png',
      '/gallery/gallery_2.png',
      '/gallery/gallery_3.png',
      '/gallery/gallery_4.png',
    ],
  },
];
